### ISSUE TITLE
1.4.0-r Spawned chests have no loot

### ISSUE THREAD

**Issue by Jorealis** [AMPZNetwork/All-The-Forge#1]
I'm poking around with the modpack to see if my friends and I would enjoy it. Usually I root through the menus in Creative, and fly around and look at structures.

However, as I was doing this, I found that none of the chests in generated structures had loot. I wondered if this was a creative-only bug, and made a new world in survival. Sadly, the same issue occurred, I tested it with and without cheats enabled on world startup.

**Comment by Jorealis** [comment]
Update! A friend and I tested the issue more thoroughly, and it seems to only affect certain chests, specifically ones in Bewitchment structures and the strange galacticraft bunkers that spawn on the overworld. (They're made of tin decoration blocks, stone slabs, and have a water filled blue glass pillar in the center with a chest inside).

**Comment by LabsZero** [comment]
Thank you for your report, The Galacticraft bunkers are something that is out of my control as i think it's a planned feature that's not quite ready yet.

**Comment by LabsZero** [comment]
I am currectly looking into this issue, not ETA on when a patch will be out.
